name: e_commerce_tools
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.4.0
  path_provider: ^2.1.5
  path: ^1.8.0
  reorderable_grid_view: ^2.2.8 
  syncfusion_flutter_xlsio : ^29.2.10
  flutter_excel: ^1.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
